# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorDonations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.IntegerField()),
                ('oid', models.IntegerField()),
                ('contact_id', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateField()),
                ('item_type', models.CharField(max_length=8)),
                ('quantity', models.IntegerField()),
                ('date_received', models.DateField(blank=True, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('retail_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('donor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('decided_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('contract', models.IntegerField()),
                ('check_number', models.CharField(blank=True, max_length=255, null=True)),
                ('thankyou_call', models.IntegerField()),
                ('thankyou_date', models.DateField(null=True, blank=True)),
                ('thankyou_captain', models.IntegerField(null=True, blank=True)),
                ('received_benefit', models.IntegerField()),
                ('thon_year', models.IntegerField()),
                ('corporate_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('corporate_contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('corporate_contact_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'donor_donations',
            },
        ),
    ]
