# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_logistics', '0002b_nullifying_sl_stb_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliesdonations',
            name='contract',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='suppliesdonations',
            name='did',
            field=models.ForeignKey(blank=True, null=True, db_column='did', on_delete=django.db.models.deletion.CASCADE, to='directory.Donor'),
        ),
        migrations.AlterField(
            model_name='suppliesdonations',
            name='item_type',
            field=models.CharField(choices=[('Monetary', 'Monetary'), ('Product', 'Product')], default='Monetary', max_length=8),
        ),
        migrations.AlterField(
            model_name='suppliesdonations',
            name='oid',
            field=models.ForeignKey(blank=True, null=True, db_column='oid', on_delete=django.db.models.deletion.CASCADE, to='directory.ThonGroup'),
        ),
        migrations.AlterField(
            model_name='suppliesdonations',
            name='received_benefit',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='suppliesdonations',
            name='thankyou_call',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='suppliesdonations',
            name='thon_year',
            field=models.PositiveSmallIntegerField(default=2017),
        ),
        migrations.AlterField(
            model_name='suppliesdonations',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
