# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 15:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0081_auto_20160720_1603'),
        ('supply_logistics', '0003_auto_20160726_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('units', models.CharField(max_length=255)),
                ('sublocation', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('item_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('current_donor', models.CharField(blank=True, max_length=255, null=True)),
                ('thon_year', models.PositiveSmallIntegerField(default=2017)),
                ('reorderthreshold', models.IntegerField(db_column='reorderThreshold', default=0)),
                ('isvisibleforrequest', models.BooleanField(db_column='isVisibleForRequest')),
                ('lastupdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='InventoryCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'inventory_categories',
            },
        ),
        migrations.CreateModel(
            name='InventoryLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'inventory_locations',
            },
        ),
        migrations.CreateModel(
            name='InventoryStockStatuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'inventory_stock_statuses',
            },
        ),
        migrations.CreateModel(
            name='InventorySubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_logistics.InventoryCategories')),
            ],
            options={
                'db_table': 'inventory_sub_categories',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='supply_logistics.InventoryCategories'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='committee_responsible',
            field=models.ForeignKey(db_column='committee_responsible', on_delete=django.db.models.deletion.CASCADE, to='directory.CommitteePosition'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='lastupdater',
            field=models.ForeignKey(db_column='lastupdater', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(db_column='location', on_delete=django.db.models.deletion.CASCADE, to='supply_logistics.InventoryLocations'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='stock',
            field=models.ForeignKey(db_column='stock', on_delete=django.db.models.deletion.CASCADE, to='supply_logistics.InventoryStockStatuses'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='subcategory',
            field=models.ForeignKey(blank=True, db_column='subcategory', null=True, on_delete=django.db.models.deletion.CASCADE, to='supply_logistics.InventorySubCategories'),
        ),
    ]
