# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_logistics', '0004_auto_20160726_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryCategories',
            new_name='InventoryCategory',
        ),
        migrations.RenameModel(
            old_name='InventoryLocations',
            new_name='InventoryLocation',
        ),
        migrations.RenameModel(
            old_name='InventoryStockStatuses',
            new_name='InventoryStockStatus',
        ),
        migrations.RenameModel(
            old_name='InventorySubCategories',
            new_name='InventorySubCategory',
        ),
        migrations.RenameModel(
            old_name='SuppliesDonations',
            new_name='SupplyDonation',
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='inventorycategory',
            options={'verbose_name_plural': 'InventoryCategories'},
        ),
        migrations.AlterModelOptions(
            name='inventorystockstatus',
            options={'verbose_name_plural': 'InventoryStockStatuses'},
        ),
        migrations.AlterModelOptions(
            name='inventorysubcategory',
            options={'verbose_name_plural': 'InventorySubCategory'},
        ),
    ]
