# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 01:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0086_organizationmember_is_chair'),
        ('supply_logistics', '0005_auto_20160728_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='committee_responsible',
            new_name='committee_responsible_old',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='stock',
            new_name='stock_status',
        ),
        migrations.AddField(
            model_name='inventory',
            name='committee_resp',
            field=models.ForeignKey(db_column='committee_resp', on_delete=django.db.models.deletion.CASCADE, to='directory.ThonGroup', blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='lastupdate',
            field=models.DateTimeField(auto_now=True),
        ),
        # migrations.AlterField(
        #     model_name='supplydonation',
        #     name='category',
        #     field=models.ForeignKey(db_column='category', default=1, on_delete=django.db.models.deletion.CASCADE, to='supply_logistics.InventoryCategory'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='supplydonation',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supplydonation',
            name='thankyou_captain',
            field=models.ForeignKey(blank=True, db_column='thankyou_captain', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
