# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 20:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supply_logistics', '0006_auto_20160802_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchandiseInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_on_hand', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'permissions': (('can_remove_change_items', 'Can Remove or Change items'), ('can_manage_merchandise_inventory', 'Can manage merchandise inventory'), ('can_use_pos_see_inventory', 'Can use POS system and see inventory')),
            },
        ),
        migrations.CreateModel(
            name='MerchandiseInventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thon_year_added', models.PositiveSmallIntegerField(default=2017)),
                ('item_name', models.CharField(max_length=255)),
                ('item_id', models.IntegerField()),
                ('item_description', models.TextField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerchandiseInventoryLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerchandiseInventoryMovements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thon_year', models.PositiveSmallIntegerField(verbose_name=2017)),
                ('item_amount', models.PositiveSmallIntegerField(default=0)),
                ('from_location', models.CharField(choices=[('South Annex', 'South Annex'), ('Store A', 'Store A'), ('Store C', 'Store C'), ('Bravo Storage', 'Bravo Storage'), ('Delta Storage', 'Delta Storage')], max_length=14)),
                ('to_location', models.CharField(choices=[('South Annex', 'South Annex'), ('Store A', 'Store A'), ('Store C', 'Store C'), ('Bravo Storage', 'Bravo Storage'), ('Delta Storage', 'Delta Storage')], max_length=14)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField()),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply_logistics.MerchandiseInventoryItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_move_merchandise_inventory', 'Can Move Merchandise Inventory'),),
            },
        ),
        migrations.AddField(
            model_name='merchandiseinventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_logistics.MerchandiseInventoryItem'),
        ),
        migrations.AddField(
            model_name='merchandiseinventory',
            name='locations',
            field=models.ManyToManyField(to='supply_logistics.MerchandiseInventoryLocation'),
        ),
    ]
